### ISSUE TITLE
Inquiry about the error in Urbanopt 0.10.0

### ISSUE THREAD

**Issue by ShikangWen2000** [urbanopt/urbanopt-cli#436]
I am trying the Urbanopt (0.9.0) in Grasshopper, however, the process fails to seek racc-1.7.1. Do you have any advice about this error? I've attached the details about the error. 

Error` executing argv: ["--bundle", "C:/Users/shika/simulation/Mass_Pike_District/Gemfile", "--bundle_path", "C:/Users/user_name/simulation/Mass_Pike_District/.bundle/install/", "run", "-w", "C:/Users/user_name/simulation/Mass_Pike_District/run/honeybee_scenario/FullServiceRestaurant_1/in.osw"]

Error: Could not find racc-1.7.1 in any of the sources in :/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
:/openstudio_cli.rb:651:in `parse_main_args'
:/openstudio_cli.rb:781:in `execute'
:/openstudio_cli.rb:1984:in `<main>'
eval:188:in `eval'
eval:188:in `require_embedded_absolute'
eval:173:in `block in require_embedded'
eval:167:in `each'
eval:167:in `require_embedded'
eval:126:in `require'
eval:3:in `<main>'

**Comment by kflemin** [comment]
This problem is due to an updated dependency in the parser gem. The latest urbanopt versions have the fix, but if you are trying to run an older project, that might be why you are still running into the issue.  If you are running URBANopt directly, the fix is to include the following line in the file named "Gemfile" within your **project directory**:
`gem 'parser', '3.2.2.2'`
as shown in https://github.com/urbanopt/urbanopt-cli/blob/develop/example_files/Gemfile#L31.  This fix must be added to each of your existing projects. 

If you are using Grasshopper/Dragonfly directly, the dependencies are managed differently, using the honeybee-openstudio-gem. The parser dependency has already been pinned there as well: https://github.com/ladybug-tools/honeybee-openstudio-gem/blob/master/lib/files/urbanopt_Gemfile#L33, so you should not be getting an error if you are using the latest version.  I believe you can update with LB Versioner.  You can get more details and support over at the Ladybug Tools Discourse page: https://discourse.ladybug.tools/.

Hope this helps!

**Comment by ShikangWen2000** [comment]
thank you. the problem have been solved after update the lb version.
