### ISSUE TITLE
Add an option to the -p command to overwrite an existing directory

### ISSUE THREAD

**Issue by chriswmackey** [urbanopt/urbanopt-cli#67]
I am finding myself having to do a lot of file acrobatics of deleting folders just to be able to ensure that the `-p` command doesn't throw the error:
```
ERROR:  there is already a directory here named [FOLDERNAME].. aborting
```
It would be very helpful to have an option on this command that allows us to overwrite the directory if we want to.

**Comment by kflemin** [comment]
@chriswmackey, do you mean like a -o or something that means overwrite is ok?  or a prompt to the user?

**Comment by vtnate** [comment]
@chriswmackey Is the difficulty that you are copying a bunch of other files in to the project directory each time you make a new one? Otherwise deleting the project folder with `rm -rf <foldername>` should be fast and simple. If it's something different, we could do either of the options @kflemin suggested. I prefer her second option, having an overwrite prompt to the user if the folder already exists.

**Comment by chriswmackey** [comment]
This is really just a suggestion and it's a low priority compared to the other bug fixes that I know in the works. But it would nice to run the `uo -p` command in a way that doesn't result in an error if the directory already exists and, in this case, it would just overwrite any files with the same name as the sample project in the directory. I don't think there needs to be a prompt to the user on the URBANopt CLI level. A `-o ` option to enable this would do the trick.

**Comment by kflemin** [comment]
let's go with the -o option then!

**Comment by tanushree04** [comment]
I can take a look at this issue
